Test

diff --git a/.github/workflows/fetch-conda-install-script.yml b/.github/workflows/fetch-conda-install-script.yml
--- a/.github/workflows/fetch-conda-install-script.yml
+++ b/.github/workflows/fetch-conda-install-script.yml
@@ -58,6 +58,21 @@ jobs:
             configure-conda.sh
             install-and-set-up-conda.sh
 
+      - name: Check files exist
+        if: steps.lookup-cache.outputs.cache-hit != 'true'
+        run: |
+          ok=true
+          for f in common.sh configure-conda.sh install-and-setup-conda.sh; do
+            if [ ! -f "$f" ]; then
+              1>&2 echo "File \"$f\" is missing!"
+              ok=false
+            fi
+          done
+
+          if [ "$ok" != true ]; then
+            exit 1
+          fi
+
       - name: Save cache
         if: steps.lookup-cache.outputs.cache-hit != 'true'
         uses: actions/cache/save@v4
@@ -67,4 +82,3 @@ jobs:
             common.sh
             configure-conda.sh
             install-and-set-up-conda.sh
-            foobar
